enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: true
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/icons8-diseño-web-filled-64.png:
    name: icons8-diseño-web-filled-64.png
    type: image/png
    size: 1615
    path: user/themes/quark/images/logo/icons8-diseño-web-filled-64.png
custom_logo_mobile:
  user/themes/quark/images/logo/icons8-diseño-web-filled-64.png:
    name: icons8-diseño-web-filled-64.png
    type: image/png
    size: 1615
    path: user/themes/quark/images/logo/icons8-diseño-web-filled-64.png
